### PR TITLE
Adding rescanned CMS data

### PR DESCRIPTION
**Pull request by FHead**
I noticed that the lumi and TAA were not folded into the previous scanned CMS data points.  Now the systematic uncertainties are a bit larger because of it

### CODE REVIEW

**Comment by raymondEhlers** [comment]
Maybe it got lost in plotting, but I included the TAA and lumi separately in the comment since they're constant (at least as far as I could tell). Did you combine them in quadrature?

**Comment by raymondEhlers** [comment]
(It looks like you probably scanned it better than I did, so it still looks like it would be an improvement regardless)

**Comment by FHead** [comment]
Yes, they are added in quadrature.  In the original text file that was used in the plotting script (not the sys.txt in the folder), I see that the systematic numbers are sometimes smaller than the TAA+Lumi, which is why I suspect it is not added.  The "rescanning" should be quite close to the actual points ;)

**Comment by raymondEhlers** [comment]
Very good! :-)

**Comment by jdmulligan** [comment]
Thanks! Yes I think in the initial version of the plot I didn't include the lumi/TAA (which were in the headers or somewhere)

@raymondEhlers maybe you can have a double check again on the ATLAS hadron scanned points since we now know these figures will directly go in the paper?

**Comment by raymondEhlers** [comment]
@jdmulligan I double checked by plotting similarly (same scale, etc). See the link. I'd say that it looks pretty reasonable (I checked point-by-point by eye). One issue we need to sort out: I can only see some of the statistical errors for points above 100 GeV. I think the statistical error is small until the last two points (I can see it starting at 100 for central), but I can't really tell. Thoughts on how to handle those? Truncate?
[atlas_hadron_RAA_comparison.pdf](https://github.com/jdmulligan/JETSCAPE-analysis/files/5476140/atlas_hadron_RAA_comparison.pdf) (original plot is embedded below)
hadronRaa

**Comment by jdmulligan** [comment]
Great, thanks!! Can you even see the statistical uncertainties for the central case for the highest two points? The third and fourth highest I can see...but perhaps we should just ignore all of them -- since this anyway isn't a very rigorous comparison, and they are preliminary results. For sake of time that's what I'd vote for -- although if you think you can scan them, then we can of course add in quadrature for those points that you can scan -- your call.

**Comment by raymondEhlers** [comment]
Agreed - I can only see the third and fourth points, but not the two highest where it really matters. For the fourth point, it's so small that adding in quadrature won't really make a difference, I think (although have to be careful with log plots). For the third point, it will matter more, but still seems to be subleading compared to the systematic. So basically only the third stat error from the highest would be meaningful, and we can't assign them for the two highest.

Given that, and that it's preliminary, and that it's going to be quite difficult to explain which points have stat errors and not (we included those we can see is kind of an odd metric, although accurate here), I would learn towards just neglecting them. However, if we can think of a concise way to describe it, I can scan those two points.

Regardless, we'll probably get questions about the last 30-40% point, but there's really nothing we can do about that

**Pull request merged**
